### ISSUE TITLE
Cannot access private name _NullSecureRandom

### ISSUE THREAD

**Issue by Kollegos** [deftomat/JustJWT#1]
Have this error trying to create rs256 verifier. 

var verifiers = {
    'RS256': toTokenVerifier(createRS256Verifier(publicKey)),
};

I fix it for me by making it public in rs256.dart file.

Also RS256 not working while this:

dependencies:
  reflectable: '1.0.1'
transformers:
- reflectable:
    entry_points: web/main.dart # The path to your main file
    formatted: true # Optional.

not in pubspec.yaml

**Comment by deftomat** [comment]
Thanks for the feedback. I will try to look at it today.

**Comment by deftomat** [comment]
I'm not sure where is the problem. ```_NullSecureRandom``` is used only inside its own library.

But you are using ```reflectable``` package, so I'm assuming that you are trying to use JustJWT in browser.

I never try this library in browser. ```_NullSecureRandom``` class extends class from [pointycastle](https://github.com/PointyCastle/pointycastle) package. As I know, they are using reflection, so maybe it is not compatible with ```reflectable``` package.

Anyway, please let me know if you are trying to use JustJWT in browser and if yes, how do you want to use it. I think it is suitable only for back-end. I cannot imagine why it should be required by a front end app (except by some online tool for parsing a JWTs). :wink:

**Comment by deftomat** [comment]
Closed due to inactivity
