### ISSUE TITLE
rsa_pkcs and pointycastle version constraint

### ISSUE THREAD

**Issue by jodinathan** [deftomat/JustJWT#2]
Hi,

This package can't be used because the version constraints in it.

Package pointycastle has no versions that match >=0.10.0+1 <0.11.0 derived from:
- just_jwt 1.3.1 depends on version ^0.10.0
- rsa_pkcs 0.1.2 depends on version >=0.10.0+1 <0.11.0

**Comment by deftomat** [comment]
@jodinathan Hi, sorry for a late response. Not sure where is a problem.
I think that both packages can use current pointycastle version (0.10.0+5)

I just try it and `pub get` installs `pointycastle 0.10.0+5`

**Comment by deftomat** [comment]
Closed due to inactivity
