### ISSUE TITLE
Support for certificates

### ISSUE THREAD

**Issue by renefloor** [deftomat/JustJWT#3]
Hi, 
I have been looking for a good JWT dart package, but haven't really found it. Yours is coming close.
I try to use firebase auth and that returns a JWT.
The formate is given here:
https://firebase.google.com/docs/auth/admin/verify-id-tokens

They are signed asymmetric and the public keys can be found here:
https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

However, they are in the format with BEGIN CERTIFICATE instead of BEGIN PUBLIC KEY and probably the content is also a bit different. Can you build support for this or help me in the direction to support this, because I can find very little documentation on this.

**Comment by deftomat** [comment]
Hi @renefloor, 
to be honest, I don't know if there is any Dart library which can extract public key from certificate.
However, you can use openssl with [Process.start](https://api.dartlang.org/stable/1.24.2/dart-io/Process-class.html) to extract it. There is an example, which describes how you can pipe data to any process and read result.

Also, there is a [library](https://github.com/deftomat/just_google_jwt_decoder), which can verify Google JWT and it is also using a public key in a slightly different format.

So, your job is just to create a stream transformer, which will receive a certificate from google servers, pipe data to openssl and then await for a public key in a requested format.

**Comment by renefloor** [comment]
Thanks @deftomat for your response.
I'll look into that. The Google JWT seems more logical than the Firebase JWT..
